// SPDX-License-Identifier: MIT
pragma solidity ^0.8.26;

import {Test} from "forge-std/Test.sol";
import {MerkleProof} from "@openzeppelin/utils/cryptography/MerkleProof.sol";

import {PonsRwaVault} from "../src/vaults/PonsRwaVault.sol";
import {RwaMerkleFixture} from "./fixtures/RwaMerkleFixture.sol";

/// @dev Proves the two halves of the payout agree.
///
///      Roots are built in TypeScript by the keeper and verified in Solidity by the vault. Those
///      are separate implementations of the same three conventions — how a leaf is encoded, that
///      leaves are hashed twice, and that pairs are hashed in sorted order — and nothing forces
///      them to stay in step. If they ever drift, a posted root still looks perfectly valid on
///      chain while every claim against it reverts, and the failure only becomes visible once real
///      dividends are already sitting unclaimable in a vault.
///
///      The fixture is generated by scripts/emit-rwa-merkle-fixture.ts from the production
///      builder, so this is the real output rather than a Solidity-side reimplementation of it.
///      No fork needed: `leafFor` is pure, so the implementation contract answers directly.
contract RwaMerkleCompatTest is Test {
    PonsRwaVault vault;

    function setUp() public {
        vault = new PonsRwaVault();
    }

    /// @dev The encoding itself. Everything else is worthless if this disagrees.
    function test_leafEncodingMatchesTypescript() public view {
        address[] memory accounts = RwaMerkleFixture.accounts();
        uint256[] memory amounts = RwaMerkleFixture.amounts();

        for (uint256 i = 0; i < accounts.length; ++i) {
            bytes32 expected = keccak256(bytes.concat(keccak256(abi.encode(accounts[i], amounts[i]))));
            assertEq(vault.leafFor(accounts[i], amounts[i]), expected, "vault leaf differs from the spec");
        }
    }

    /// @dev Every proof the keeper would hand a holder must satisfy the exact verifier the vault
    ///      calls. Five leaves, so the tree carries an unpaired node through more than one level.
    function test_everyGeneratedProofVerifies() public view {
        address[] memory accounts = RwaMerkleFixture.accounts();
        uint256[] memory amounts = RwaMerkleFixture.amounts();
        assertEq(accounts.length, RwaMerkleFixture.COUNT, "fixture is internally inconsistent");
        assertEq(accounts.length % 2, 1, "fixture must have an odd leaf count to be worth testing");

        for (uint256 i = 0; i < accounts.length; ++i) {
            bytes32 leaf = vault.leafFor(accounts[i], amounts[i]);
            assertTrue(
                MerkleProof.verify(RwaMerkleFixture.proofAt(i), RwaMerkleFixture.ROOT, leaf),
                "a proof produced by the keeper was rejected by the vault's verifier"
            );
        }
    }

    /// @dev The allocation must sum to exactly the round total. Under-allocating strands the
    ///      difference until the round expires; over-allocating leaves the last claimants finding
    ///      the round already empty.
    function test_allocationSumsToTheRoundTotal() public pure {
        uint256[] memory amounts = RwaMerkleFixture.amounts();

        uint256 sum;
        for (uint256 i = 0; i < amounts.length; ++i) {
            sum += amounts[i];
        }

        assertEq(sum, RwaMerkleFixture.TOTAL, "allocation does not add up to the round");
    }

    /// @dev A proof is only worth anything if it fails for the wrong claim.
    function test_proofsDoNotVerifyForTheWrongClaimant() public view {
        address[] memory accounts = RwaMerkleFixture.accounts();
        uint256[] memory amounts = RwaMerkleFixture.amounts();

        // Account 0's proof, presented for account 1's leaf.
        bytes32 otherLeaf = vault.leafFor(accounts[1], amounts[1]);
        assertFalse(
            MerkleProof.verify(RwaMerkleFixture.proofAt(0), RwaMerkleFixture.ROOT, otherLeaf),
            "a proof verified for a leaf it does not belong to"
        );

        // The right claimant asking for more than they were allocated.
        bytes32 inflated = vault.leafFor(accounts[0], amounts[0] + 1);
        assertFalse(
            MerkleProof.verify(RwaMerkleFixture.proofAt(0), RwaMerkleFixture.ROOT, inflated),
            "an inflated amount verified against the root"
        );
    }
}
