// SPDX-License-Identifier: MIT
pragma solidity ^0.8.26;

/// @dev GENERATED by scripts/emit-rwa-merkle-fixture.ts — do not edit by hand.
///
///      A real allocation tree produced by the keeper's own TypeScript, captured so the
///      Solidity side can prove it accepts what production will actually post.
library RwaMerkleFixture {
    bytes32 internal constant ROOT = 0xf4ca3a270e1b1caae9802db6055eb256a0155c54cbd918c3e0c1e41283169cfa;
    uint256 internal constant TOTAL = 13435676894782655;
    uint256 internal constant COUNT = 5;

    function accounts() internal pure returns (address[] memory out) {
        out = new address[](5);
        out[0] = 0x2222222222222222222222222222222222222222;
        out[1] = 0x3333333333333333333333333333333333333333;
        out[2] = 0x897ac30f73Ba92E1EFbC1dF1e67f8b5F4b3ECD2b;
        out[3] = 0xCD0875124415A61D0d9082496AE8e88c2d55a642;
        out[4] = 0xFFfFfFffFFfffFFfFFfFFFFFffFFFffffFfFFFfF;
    }

    function amounts() internal pure returns (uint256[] memory out) {
        out = new uint256[](5);
        out[0] = 10810268556983467;
        out[1] = 772161344838627;
        out[2] = 1389891810601340;
        out[3] = 463296806903176;
        out[4] = 58375456045;
    }

    function proofAt(uint256 index) internal pure returns (bytes32[] memory out) {
        if (index == 0) {
            out = new bytes32[](3);
            out[0] = 0x27801fe87edfbd0d24e698e845f6520311522b9a385d3718d59b4f66fdaaf35e;
            out[1] = 0xa35c7500c076fe74c63af2d50485217139a5614d56fad9128c534b2f1505bd7d;
            out[2] = 0xe8a39b41a683cdc6d98b0d502fab9f5c79d5a3d72459644790d26f648953d3a5;
            return out;
        }
        if (index == 1) {
            out = new bytes32[](3);
            out[0] = 0xe11cb2ea2453fe9461710a9360f86f911f289b82e762de98534452f5ffb199ae;
            out[1] = 0xa35c7500c076fe74c63af2d50485217139a5614d56fad9128c534b2f1505bd7d;
            out[2] = 0xe8a39b41a683cdc6d98b0d502fab9f5c79d5a3d72459644790d26f648953d3a5;
            return out;
        }
        if (index == 2) {
            out = new bytes32[](3);
            out[0] = 0x252f6cd13d3c69ab106335be4b8d1c2a187c0181883a57ec2fffeee6783077c9;
            out[1] = 0x489bfb99b92cf9633e5f43941c18fb029ba4c5fb3f029849d2b67715b10e162f;
            out[2] = 0xe8a39b41a683cdc6d98b0d502fab9f5c79d5a3d72459644790d26f648953d3a5;
            return out;
        }
        if (index == 3) {
            out = new bytes32[](3);
            out[0] = 0x3df4bc8f7fd879b908902c336b0a6200b3d305ebe5f0cec9c6a8e6fa4dfd2be9;
            out[1] = 0x489bfb99b92cf9633e5f43941c18fb029ba4c5fb3f029849d2b67715b10e162f;
            out[2] = 0xe8a39b41a683cdc6d98b0d502fab9f5c79d5a3d72459644790d26f648953d3a5;
            return out;
        }
        if (index == 4) {
            out = new bytes32[](1);
            out[0] = 0x9c4d52d8aa12b32b9d4192216ff3c210c4526fbf52ee2c0fa11f327cf6b4ac47;
            return out;
        }
        revert("no such fixture index");
    }
}
