[profile.default]
src = "src"
out = "out"
libs = ["lib"]
evm_version = "cancun"
solc_version = "0.8.26"
optimizer = true
optimizer_runs = 99999

[rpc_endpoints]
robinhood = "https://rpc.mainnet.chain.robinhood.com"

[etherscan]
robinhood = { key = "${BLOCKSCOUT_API_KEY}", url = "https://robinhoodchain.blockscout.com/api", chain = 4663 }
