/**
 * Prints the exact transaction the launch form would ask a wallet to sign.
 *
 * Goes through the same `buildLaunchMetadata` and `encodeLaunchWithVaultTransaction`
 * the browser calls, so this is the real calldata rather than a reconstruction of
 * it. `contracts/test/WebsiteLaunch.fork.t.sol` replays these blobs against the
 * deployed launcher on a fork, which is the only way to prove the browser path
 * works end to end: TypeScript cannot execute the contract and Solidity cannot
 * encode what the browser encodes.
 *
 * Regenerate the literals in that test whenever the form or a Config changes.
 */
import { mkdirSync, writeFileSync } from 'fs';
import { dirname } from 'path';

import { buildLaunchMetadata } from '../src/lib/pons/launch';
import type { LaunchFormInput } from '../src/lib/pons/types';
import { PONSVAULT_DEPLOYMENT } from '../src/lib/pons/deployments';
import { encodeLaunchWithVaultTransaction } from '../src/lib/pons/vault';

const CREATOR = '0x45e9E2A1BB0798dd3722c24f6bb31112dAf6DcD5' as const;

const base = {
  name: 'Website Launch',
  symbol: 'WEB',
  description: 'Launched through the form, exactly as a user would.',
  imageUri: 'ipfs://bafkreiplaceholderplaceholderplaceholderplaceholder',
  twitter: 'ponsvault',
  telegram: 'ponsvault',
  website: 'https://ponsvault.com',
  devBuyEth: '0.05',
  vaultTemplate: 'buyback-burn',
  vaultBurnPercent: '80',
  vaultTreasury: '0x1111111111111111111111111111111111111111',
  vaultMinHarvestEth: '0.025',
  vaultStakingLockDays: '0',
} as unknown as LaunchFormInput;

const cases: Array<[string, string, LaunchFormInput]> = [
  ['BUYBACK_WITH_DEV_BUY', 'buyback 80/20, 0.05 ETH dev buy', base],
  [
    'BUYBACK_FULL_BURN',
    'buyback 100% burn, no treasury',
    { ...base, vaultBurnPercent: '100', vaultTreasury: '' },
  ],
  [
    'STAKING_THIRTY_DAY_LOCK',
    'staking, 30 day lock',
    { ...base, vaultTemplate: 'staking', vaultStakingLockDays: '30' } as LaunchFormInput,
  ],
  ['BUYBACK_NO_DEV_BUY', 'buyback 80/20, no dev buy', { ...base, devBuyEth: '' }],
];

const lines: string[] = [
  '// SPDX-License-Identifier: MIT',
  'pragma solidity ^0.8.26;',
  '',
  '// GENERATED by scripts/emit-launch-calldata.ts - do not edit by hand.',
  '//',
  '// The literal transactions the launch form asks a wallet to sign, produced by the',
  '// same encoder the browser runs. WebsiteLaunch.fork.t.sol replays them against the',
  '// deployed launcher, which is the only way to prove the browser path actually works:',
  '// TypeScript cannot execute the contract, and Solidity cannot encode what the',
  '// browser encodes. Regenerate whenever the form or a Config changes.',
  '',
  `address constant GENERATED_FOR_LAUNCHER = ${PONSVAULT_DEPLOYMENT.launcher};`,
  '',
  'library LaunchCalldata {',
];

for (const [name, label, input] of cases) {
  // Exactly what the form does: the launcher is passed as the fee wallet override,
  // and the contract overwrites it with the creator.
  const metadata = buildLaunchMetadata(input, CREATOR, PONSVAULT_DEPLOYMENT.launcher as `0x${string}`);
  const salt = `0x${Buffer.from(name.padEnd(32, ' ')).subarray(0, 32).toString('hex')}` as `0x${string}`;
  const calldata = encodeLaunchWithVaultTransaction(metadata, input, salt);

  lines.push(`    /// ${label}. dev buy: ${input.devBuyEth || '0'} ETH`);
  lines.push(`    bytes internal constant ${name} = hex"${calldata.slice(2)}";`);
  lines.push('');
}

lines.push('}');

const out = 'contracts/test/fixtures/LaunchCalldata.sol';
mkdirSync(dirname(out), { recursive: true });
writeFileSync(out, `${lines.join('\n')}\n`);
console.log(`wrote ${out} for launcher ${PONSVAULT_DEPLOYMENT.launcher}`);
