/**
 * Emits a real allocation tree, built by the code that will build them in
 * production, as a Solidity fixture.
 *
 * The keeper builds roots in TypeScript and the vault verifies them in
 * Solidity with OpenZeppelin's MerkleProof. Nothing checks that those two
 * agree — and if they ever disagree, every root posted still looks valid,
 * every claim reverts, and the failure only surfaces once real dividends are
 * already sitting unclaimable in a vault. Writing the tree out and verifying it
 * from the other side closes that seam.
 *
 *   npx tsx --conditions=react-server scripts/emit-rwa-merkle-fixture.ts \
 *     > contracts/test/fixtures/RwaMerkleFixture.sol
 */
import type { Address } from 'viem';

import { allocatePro, type HolderBalance } from '@/lib/rwa/holders';
import { buildAllocation } from '@/lib/rwa/merkle';

// Six holders, one of them dust. The dust share rounds to nothing and is
// dropped, leaving five leaves — an odd count, so the tree has to promote an
// unpaired node at more than one level. An even count would never exercise
// that path, and it is the part of the builder most likely to be wrong.
const HOLDERS: HolderBalance[] = [
  { account: '0x897ac30f73Ba92E1EFbC1dF1e67f8b5F4b3ECD2b' as Address, balance: 1_000_000n * 10n ** 18n },
  { account: '0xCD0875124415A61D0d9082496AE8e88c2d55a642' as Address, balance: 333_333n * 10n ** 18n },
  { account: '0x1111111111111111111111111111111111111111' as Address, balance: 1n },
  { account: '0x2222222222222222222222222222222222222222' as Address, balance: 7_777_777n * 10n ** 18n },
  { account: '0x3333333333333333333333333333333333333333' as Address, balance: 555_555n * 10n ** 18n },
  { account: '0xFFfFfFffFFfffFFfFFfFFFFFffFFFffffFfFFFfF' as Address, balance: 42n * 10n ** 18n },
];

// A deliberately awkward amount, so the remainder handling is exercised rather
// than dividing cleanly.
const ROUND_TOTAL = 13_435_676_894_782_655n;

function main() {
  const totalHeld = HOLDERS.reduce((sum, h) => sum + h.balance, 0n);
  const allocation = allocatePro(HOLDERS, totalHeld, ROUND_TOTAL);
  const { root, claims, total } = buildAllocation(allocation);

  if (total !== ROUND_TOTAL) {
    throw new Error(`allocation sums to ${total}, expected ${ROUND_TOTAL}`);
  }

  const entries = [...claims.values()];

  const lines: string[] = [
    '// SPDX-License-Identifier: MIT',
    'pragma solidity ^0.8.26;',
    '',
    '/// @dev GENERATED by scripts/emit-rwa-merkle-fixture.ts — do not edit by hand.',
    '///',
    '///      A real allocation tree produced by the keeper\'s own TypeScript, captured so the',
    '///      Solidity side can prove it accepts what production will actually post.',
    'library RwaMerkleFixture {',
    `    bytes32 internal constant ROOT = ${root};`,
    `    uint256 internal constant TOTAL = ${total};`,
    `    uint256 internal constant COUNT = ${entries.length};`,
    '',
    '    function accounts() internal pure returns (address[] memory out) {',
    `        out = new address[](${entries.length});`,
    ...entries.map((c, i) => `        out[${i}] = ${c.account};`),
    '    }',
    '',
    '    function amounts() internal pure returns (uint256[] memory out) {',
    `        out = new uint256[](${entries.length});`,
    ...entries.map((c, i) => `        out[${i}] = ${c.amount};`),
    '    }',
    '',
    '    function proofAt(uint256 index) internal pure returns (bytes32[] memory out) {',
  ];

  entries.forEach((claim, i) => {
    lines.push(`        if (index == ${i}) {`);
    lines.push(`            out = new bytes32[](${claim.proof.length});`);
    claim.proof.forEach((node, j) => lines.push(`            out[${j}] = ${node};`));
    lines.push('            return out;');
    lines.push('        }');
  });

  lines.push('        revert("no such fixture index");');
  lines.push('    }');
  lines.push('}');

  console.log(lines.join('\n'));
}

main();
